# This is a basic workflow to help you get started with Actions

name: stage-reset

defaults:
  run:
    working-directory: ./.github/actions/merge-staging-pull-requests

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run reset script
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}
          git checkout -b stage
          git push -f origin stage
      # Runs a set of commands using the runners shell
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      
      - name: Build stuffs
        run: |
          npm install @actions/core
          npm install @octokit/action

      - name: mergeStagingPRs
        uses: ./.github/actions/merge-staging-pull-requests
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Deploy merged PRs
        run: |
          git checkout stage
          git pull origin/stage
          git push origin stage